language: python
sudo: false
python:
  - 2.7
branches:
  only:
    - master
    - develop
install:
  - "pip install numpy"
  - "pip install coverage"
  - "pip install -r requirements.txt"
script: nosetests tests --with-coverage --cover-package=b2ac

